# Generated by Django 4.2 on 2025-12-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('date_joined',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
